[tool.black]
line-length = 80
target-version = ['py312']
skip-string-normalization = true
exclude = 'models.py'

[tool.pytest.ini_options]
pythonpath = ['.']
asyncio_mode = 'auto'
asyncio_default_fixture_loop_scope = 'session'
